name: BuildPage

on:
  push:
    branches:
      - main

jobs:
  build_page:
    env:
      my_secret: ${{secrets.PUSHPAGE}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.8'
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Run Build Utils
        run: |
          pip install -r ./utils/image_series_rescaler/requirements.txt
          python3 ./utils/image_series_rescaler/script.py test_matrix_app/assets

      - name: Build page with Flutter
        run: |
          flutter pub get
          flutter build web --release --pwa-strategy=none
        working-directory: test_matrix_app

      - name: Remove base tag for GitHub Pages
        run: sed -i'' -e '/<base href/d' build/web/index.html
        working-directory: test_matrix_app

      - name: Create CNAME file
        run: echo "testmatrix.shardware.net" > CNAME
        working-directory: test_matrix_app/build/web

      - name: Push Build to Github Pages
        run: |
          git init
          git branch -m main
          git config --global user.email Builder@testmatrix.shardware.net
          git config --global user.name Builder
          git remote add origin https://${{secrets.PUSHPAGE}}@github.com/SkyDev125/TestMatrixPage.git
          git add --all
          git commit -m "update"
          git push origin main -f
        working-directory: test_matrix_app/build/web

      - name: Print versions
        run: |
          git --version
          flutter --version
          python3 --version
          pip --version
        working-directory: test_matrix_app/build/web
